In [35]:
import numpy as np
import pandas as pd

In [36]:
n_rows=1000
data ={
'size':np.random.choice (['big','small','medium'],n_rows),
'colour': np.random.choice( ['green','blue','red'],n_rows),
'material': np.random.choice(['plastic','metal','wood'],n_rows),
'price' : np.random.randint(10,500,n_rows)
}

df=pd.DataFrame(data)

In [37]:
df=pd.DataFrame(data)

In [38]:
df

       size colour material  price
0       big    red  plastic    303
1     small   blue     wood    269
2    medium    red     wood    115
3    medium   blue    metal    234
4     small   blue     wood    315
..      ...    ...      ...    ...
995   small   blue  plastic    151
996     big   blue    metal    131
997     big  green  plastic    427
998  medium    red    metal    120
999   small  green     wood     98

[1000 rows x 4 columns]

In [39]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [40]:
x = df.drop(columns='price')
y=df.price
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [41]:
label_encoder = LabelEncoder()
updated_xtrain = label_encoder.fit_transform(xtrain['colour'])

In [42]:
label_encoder.fit_transform(xtrain['colour'])

array([0, 2, 1, 2, 0, 1, 0, 0, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 2, 1,
       0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 2, 0,
       0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2,
       1, 1, 2, 0, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 1, 1, 2, 2, 0, 2, 2, 0,
       1, 1, 1, 2, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1,
       1, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 1, 1, 0, 1, 1,
       2, 2, 2, 1, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 1, 2, 0,
       0, 1, 1, 1, 2, 2, 0, 0, 2, 1, 2, 2, 1, 1, 2, 0, 1, 1, 2, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 1, 1,
       2, 1, 2, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 1, 0, 2, 2, 1, 2, 2, 2,
       0, 0, 2, 0, 2, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 1, 2, 2, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0, 2,
       1, 1, 1, 2, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2,
       1, 2, 2, 0, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 2, 2, 0, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0,
       0, 2, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 1, 1, 2, 1, 1, 2, 0, 0, 2, 2, 1,
       2, 0, 0, 1, 2, 2, 0, 1, 1, 0, 0, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 0, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 2, 1, 2, 2, 2, 1, 1, 1, 2, 0, 2, 0, 2, 2, 1, 2, 0, 2, 1, 0, 1,
       1, 2, 1, 1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0,
       1, 0, 0, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 2,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0,
       1, 0, 2, 2, 2, 2, 0, 0, 0, 1, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 0,
       0, 2, 0, 0, 1, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 2, 0, 1, 2, 2, 2, 2,
       2, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1, 0, 1,
       0, 1, 1, 1, 2, 0, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
       0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 1, 2, 0, 2, 1, 1, 1, 2, 0, 1, 2,
       1, 2, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2,
       1, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 0, 1,
       0, 2, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 1, 1, 0, 0, 2, 2, 0, 2,
       1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 1,
       1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 2, 1, 2, 1, 1, 0,
       2, 0, 2, 1, 1, 1, 2, 0])

In [43]:
# label_encoder.transform(xtest) #ValueError: y should be a 1d array, got an array of shape (200, 3) instead.

In [44]:
# new_input
new_input = ['red','red',]
label_encoder.transform(new_input)

array([2, 2])

In [45]:
# OneHot encoder
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=True)
values= encoder.fit_transform(xtrain)
#toarray
values = values.toarray()

In [46]:
# encoder = OneHotEncoder(sparse_output=False)
# values= encoder.fit_transform(xtrain)
# values = values.toarray()

In [47]:
columns = encoder.get_feature_names_out()

In [48]:
pd.DataFrame(values,columns=columns)

,size_big,size_medium,size_small,colour_blue,colour_green,colour_red,material_metal,material_plastic,material_wood
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
796,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
797,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
798,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
799,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [49]:

'''ValueError: encoder.transform(xtest[['colour','size']])
 The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- materia'''

encoder.transform(xtest)  # valid

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 600 stored elements and shape (200, 9)>

In [50]:
'''new_input = [['red','large'],['blue','small']]'''
# '''encoder.transform(new_input)'''''  ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.

"new_input = [['red','large'],['blue','small']]"

In [51]:
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
updated_xtrain = encoder.fit_transform(xtrain)
new_input = [['red1','large1','plastic'],['blue','small','wood']]
encoder.transform(new_input)

c:\Users\Admin\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [52]:
encoder.get_feature_names_out()

array(['size_big', 'size_medium', 'size_small', 'colour_blue',
       'colour_green', 'colour_red', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

# 26/06/2026

xtest = having less sasmples  using in transform only

# syntax
1) objname.fit_transform(xtrain)     this correct syntax , 
2) objname.fit_transform(xtest)      wrong, 
3) objname.fit_transform([values])   wrong, 
4) objname.fit_transform(x)          wrong  ,

these two or common techniques syntax

1) obj.fittransform(xtrain)
2) object.transform(xtest)
3) objname.transform([new input])

# odrinal encoder
 based on order it will works

In [53]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
updated_xtrain = encoder.fit_transform(xtrain)
updated_xtrain

array([[0., 0., 1.],
       [0., 2., 2.],
       [0., 1., 0.],
       ...,
       [2., 1., 1.],
       [1., 2., 1.],
       [0., 0., 1.]], shape=(800, 3))

In [54]:
# updated_xtrain = encoder.fit_transform (xtrain['colour']) 
# updated_xtrain
# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row

In [55]:
encoder.get_feature_names_out()

array(['size', 'colour', 'material'], dtype=object)

In [56]:
updated_xtest = encoder.transform(xtest)
updated_xtest

array([[2., 1., 1.],
       [1., 2., 1.],
       [0., 0., 0.],
       [0., 2., 2.],
       [2., 1., 1.],
       [2., 0., 1.],
       [0., 2., 2.],
       [2., 2., 2.],
       [0., 0., 2.],
       [0., 1., 1.],
       [2., 0., 2.],
       [2., 1., 2.],
       [0., 0., 2.],
       [0., 0., 0.],
       [1., 2., 2.],
       [2., 1., 0.],
       [0., 1., 2.],
       [1., 0., 1.],
       [2., 1., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 1.],
       [0., 0., 0.],
       [1., 2., 2.],
       [1., 2., 1.],
       [2., 2., 2.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 1., 2.],
       [1., 2., 0.],
       [1., 1., 2.],
       [2., 1., 2.],
       [1., 0., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 2., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [2., 1., 0.],
       [1., 2., 0.],
       [2., 1., 0.],
       [0., 2., 1.],
       [1., 1., 1.],
       [1., 2., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [1., 2., 2.],
       [2., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [0., 2., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [1., 2., 2.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [1., 1., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [2., 0., 2.],
       [1., 0., 0.],
       [0., 2., 1.],
       [2., 0., 0.],
       [0., 2., 2.],
       [1., 2., 1.],
       [2., 2., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 2., 0.],
       [0., 2., 1.],
       [0., 0., 2.],
       [2., 2., 0.],
       [2., 0., 2.],
       [2., 2., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 2., 1.],
       [2., 2., 1.],
       [1., 2., 2.],
       [1., 0., 2.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 2.],
       [1., 2., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 2.],
       [1., 2., 1.],
       [2., 2., 2.],
       [2., 0., 1.],
       [2., 1., 0.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 0.],
       [1., 2., 1.],
       [2., 2., 1.],
       [1., 1., 2.],
       [2., 1., 0.],
       [1., 2., 0.],
       [1., 2., 2.],
       [1., 1., 1.],
       [0., 1., 1.],
       [2., 1., 2.],
       [0., 1., 1.],
       [2., 2., 0.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 0., 2.],
       [0., 2., 0.],
       [2., 0., 1.],
       [0., 0., 2.],
       [0., 2., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 2., 1.],
       [2., 1., 2.],
       [1., 1., 0.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [2., 0., 0.],
       [2., 1., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [2., 0., 2.],
       [0., 1., 2.],
       [2., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [1., 0., 2.],
       [2., 0., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [0., 2., 1.],
       [0., 2., 2.],
       [1., 0., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 2., 2.],
       [0., 1., 2.],
       [2., 2., 2.],
       [1., 1., 0.],
       [0., 0., 0.],
       [1., 2., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [1., 1., 2.],
       [2., 2., 1.],
       [0., 1., 0.],
       [1., 2., 2.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 1., 1.],
       [1., 1., 2.],
       [2., 0., 1.],
       [1., 2., 1.],
       [0., 2., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [2., 0., 2.],
       [2., 2., 2.],
       [1., 0., 0.],
       [1., 1., 2.],
       [0., 2., 2.],
       [1., 0., 0.],
       [2., 0., 0.],
       [1., 1., 1.]])

In [57]:
# updated_xtest = encoder.transform(xtest['colour'])
# updated_xtest
# ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [58]:
xtrain

       size colour material
29      big   blue  plastic
535     big    red     wood
695     big  green    metal
557     big    red  plastic
836  medium   blue     wood
..      ...    ...      ...
106   small  green    metal
270     big  green    metal
860   small  green  plastic
435  medium    red  plastic
102     big   blue  plastic

[800 rows x 3 columns]

In [59]:
encoder = OrdinalEncoder(handle_unknown='error')
encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain = encoder.fit_transform(xtrain)
updated_xtest = encoder.transform(xtest)
new_data = [['white','small','wood'],['red','small','wood']]
new_data = pd.DataFrame(data=[['white','small','wood'],['red','small','wood']],columns=['size','colour','materia'])
updated_new_data = encoder.transform(new_input)
updated_new_data

c:\Users\Admin\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1., -1.,  1.],
       [-1., -1.,  2.]])

In [60]:
xtrain['colour'].unique()

<StringArray>
['blue', 'red', 'green']
Length: 3, dtype: str

In [61]:
'''ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).'''
'''encoder = OrdinalEncoder(categories=[['green', 'yellow', 'blue', 'red']],handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain = encoder.fit_transform(xtrain)
encoder.fit_transform(xtrain)
why? xtrain having 3 cols categories=[[col_orders]] shape mis matching 
Whwn '''

"encoder = OrdinalEncoder(categories=[['green', 'yellow', 'blue', 'red']],handle_unknown='use_encoded_value',unknown_value=-1)\nupdated_xtrain = encoder.fit_transform(xtrain)\nencoder.fit_transform(xtrain)\nwhy? xtrain having 3 cols categories=[[col_orders]] shape mis matching \nWhwn "

In [62]:
encoder = OrdinalEncoder(categories=[['blue', 'red', 'green'],['metal', 'wood', 'plastic'],['small', 'medium', 'big']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       ...,
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]], shape=(800, 3))

In [63]:
encoder.transform(xtrain)

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       ...,
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]], shape=(800, 3))

In [64]:
from category_encoders import TargetEncoder

object cols = list of column names and this is not valid 
ob_cols=[] ❌

In [65]:
obj_cols = xtrain.select_dtypes(include='object').columns
# num_cols =

C:\Users\Admin\AppData\Local\Temp\ipykernel_6904\3579727761.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = xtrain.select_dtypes(include='object').columns

In [66]:
encoder=TargetEncoder(cols=['colour'],handle_unknown='values')
encoder.fit_transform(xtrain,ytrain)

       size      colour material
29      big  253.928030  plastic
535     big  254.503650     wood
695     big  239.572519    metal
557     big  254.503650  plastic
836  medium  253.928030     wood
..      ...         ...      ...
106   small  239.572519    metal
270     big  239.572519    metal
860   small  239.572519  plastic
435  medium  254.503650  plastic
102     big  253.928030  plastic

[800 rows x 3 columns]

In [67]:
encoder.transform(xtest)

       size      colour material
521   small  239.572519  plastic
737  medium  254.503650  plastic
740     big  253.928030    metal
660     big  254.503650     wood
411   small  239.572519  plastic
..      ...         ...      ...
408  medium  239.572519     wood
332     big  254.503650     wood
208  medium  253.928030    metal
613   small  253.928030    metal
78   medium  239.572519  plastic

[200 rows x 3 columns]

In [68]:
new_input = [['red','small','wood1']]
new_input = pd.DataFrame({'colour':['red'],'size':['small'],'material':['wood']})
encoder.transform(new_input)

      colour   size material
0  254.50365  small     wood